# Generated by Django 5.1.4 on 2024-12-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wcb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
