# Generated by Django 5.1.4 on 2024-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcb', '0002_modelmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelMetrics',
        ),
    ]
