# Generated by Django 5.1.4 on 2024-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcb', '0003_nyzipcode_delete_modelmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyzipcode',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
