# Generated by Django 5.1.4 on 2024-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcb', '0004_alter_nyzipcode_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyzipcode',
            name='encoded_value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
