# Generated by Django 5.1.4 on 2024-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcb', '0005_nyzipcode_encoded_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyzipcode',
            name='county',
        ),
        migrations.AlterField(
            model_name='nyzipcode',
            name='encoded_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nyzipcode',
            name='zip_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
