# Generated by Django 5.1.4 on 2024-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcb', '0006_remove_nyzipcode_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=100)),
                ('encoded_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
