FEATURE_ORDER = fields = ['Age at Injury',
 'Average Weekly Wage',
 'Birth Year',
 'Carrier Name',
 'IME-4 Count',
 'Zip Code',
 'Number of Dependents',
 'Has IME-4',
 'Accident Date_Year',
 'Accident Date_Month',
 'Accident Date_Day',
 'Accident Date_DayOfWeek',
 'Assembly Date_Year',
 'Assembly Date_Month',
 'Assembly Date_Day',
 'Assembly Date_DayOfWeek',
 'C-2 Date_Year',
 'C-2 Date_Month',
 'C-2 Date_Day',
 'C-2 Date_DayOfWeek',
 'Alternative Dispute Resolution_N',
 'Alternative Dispute Resolution_U',
 'Alternative Dispute Resolution_Y',
 'Attorney/Representative_N',
 'Attorney/Representative_Y',
 'Carrier Type_1A. PRIVATE',
 'Carrier Type_2A. SIF',
 'Carrier Type_3A. SELF PUBLIC',
 'Carrier Type_4A. SELF PRIVATE',
 'Carrier Type_5A. SPECIAL FUND - CONS. COMM. (SECT. 25-A)',
 'Carrier Type_5C. SPECIAL FUND - POI CARRIER WCB MENANDS',
 'Carrier Type_5D. SPECIAL FUND - UNKNOWN',
 'Carrier Type_UNKNOWN',
 'County of Injury_ALBANY',
 'County of Injury_ALLEGANY',
 'County of Injury_BRONX',
 'County of Injury_BROOME',
 'County of Injury_CATTARAUGUS',
 'County of Injury_CAYUGA',
 'County of Injury_CHAUTAUQUA',
 'County of Injury_CHEMUNG',
 'County of Injury_CHENANGO',
 'County of Injury_CLINTON',
 'County of Injury_COLUMBIA',
 'County of Injury_CORTLAND',
 'County of Injury_DELAWARE',
 'County of Injury_DUTCHESS',
 'County of Injury_ERIE',
 'County of Injury_ESSEX',
 'County of Injury_FRANKLIN',
 'County of Injury_FULTON',
 'County of Injury_GENESEE',
 'County of Injury_GREENE',
 'County of Injury_HAMILTON',
 'County of Injury_HERKIMER',
 'County of Injury_JEFFERSON',
 'County of Injury_KINGS',
 'County of Injury_LEWIS',
 'County of Injury_LIVINGSTON',
 'County of Injury_MADISON',
 'County of Injury_MONROE',
 'County of Injury_MONTGOMERY',
 'County of Injury_NASSAU',
 'County of Injury_NEW YORK',
 'County of Injury_NIAGARA',
 'County of Injury_ONEIDA',
 'County of Injury_ONONDAGA',
 'County of Injury_ONTARIO',
 'County of Injury_ORANGE',
 'County of Injury_ORLEANS',
 'County of Injury_OSWEGO',
 'County of Injury_OTSEGO',
 'County of Injury_PUTNAM',
 'County of Injury_QUEENS',
 'County of Injury_RENSSELAER',
 'County of Injury_RICHMOND',
 'County of Injury_ROCKLAND',
 'County of Injury_SARATOGA',
 'County of Injury_SCHENECTADY',
 'County of Injury_SCHOHARIE',
 'County of Injury_SCHUYLER',
 'County of Injury_SENECA',
 'County of Injury_ST. LAWRENCE',
 'County of Injury_STEUBEN',
 'County of Injury_SUFFOLK',
 'County of Injury_SULLIVAN',
 'County of Injury_TIOGA',
 'County of Injury_TOMPKINS',
 'County of Injury_ULSTER',
 'County of Injury_UNKNOWN',
 'County of Injury_WARREN',
 'County of Injury_WASHINGTON',
 'County of Injury_WAYNE',
 'County of Injury_WESTCHESTER',
 'County of Injury_WYOMING',
 'County of Injury_YATES',
 'COVID-19 Indicator_N',
 'COVID-19 Indicator_Y',
 'District Name_ALBANY',
 'District Name_BINGHAMTON',
 'District Name_BUFFALO',
 'District Name_HAUPPAUGE',
 'District Name_NYC',
 'District Name_ROCHESTER',
 'District Name_STATEWIDE',
 'District Name_SYRACUSE',
 'Gender_F',
 'Gender_M',
 'Gender_U',
 'Gender_X',
 'Industry Code_11.0',
 'Industry Code_21.0',
 'Industry Code_22.0',
 'Industry Code_23.0',
 'Industry Code_31.0',
 'Industry Code_32.0',
 'Industry Code_33.0',
 'Industry Code_42.0',
 'Industry Code_44.0',
 'Industry Code_45.0',
 'Industry Code_48.0',
 'Industry Code_49.0',
 'Industry Code_51.0',
 'Industry Code_52.0',
 'Industry Code_53.0',
 'Industry Code_54.0',
 'Industry Code_55.0',
 'Industry Code_56.0',
 'Industry Code_61.0',
 'Industry Code_62.0',
 'Industry Code_71.0',
 'Industry Code_72.0',
 'Industry Code_81.0',
 'Industry Code_92.0',
 'Industry Code_nan',
 'Medical Fee Region_I',
 'Medical Fee Region_II',
 'Medical Fee Region_III',
 'Medical Fee Region_IV',
 'Medical Fee Region_UK',
 'WCIO Cause of Injury Code_1.0',
 'WCIO Cause of Injury Code_10.0',
 'WCIO Cause of Injury Code_11.0',
 'WCIO Cause of Injury Code_12.0',
 'WCIO Cause of Injury Code_13.0',
 'WCIO Cause of Injury Code_14.0',
 'WCIO Cause of Injury Code_15.0',
 'WCIO Cause of Injury Code_16.0',
 'WCIO Cause of Injury Code_17.0',
 'WCIO Cause of Injury Code_18.0',
 'WCIO Cause of Injury Code_19.0',
 'WCIO Cause of Injury Code_2.0',
 'WCIO Cause of Injury Code_20.0',
 'WCIO Cause of Injury Code_25.0',
 'WCIO Cause of Injury Code_26.0',
 'WCIO Cause of Injury Code_27.0',
 'WCIO Cause of Injury Code_28.0',
 'WCIO Cause of Injury Code_29.0',
 'WCIO Cause of Injury Code_3.0',
 'WCIO Cause of Injury Code_30.0',
 'WCIO Cause of Injury Code_31.0',
 'WCIO Cause of Injury Code_32.0',
 'WCIO Cause of Injury Code_33.0',
 'WCIO Cause of Injury Code_4.0',
 'WCIO Cause of Injury Code_40.0',
 'WCIO Cause of Injury Code_41.0',
 'WCIO Cause of Injury Code_45.0',
 'WCIO Cause of Injury Code_46.0',
 'WCIO Cause of Injury Code_47.0',
 'WCIO Cause of Injury Code_48.0',
 'WCIO Cause of Injury Code_5.0',
 'WCIO Cause of Injury Code_50.0',
 'WCIO Cause of Injury Code_52.0',
 'WCIO Cause of Injury Code_53.0',
 'WCIO Cause of Injury Code_54.0',
 'WCIO Cause of Injury Code_55.0',
 'WCIO Cause of Injury Code_56.0',
 'WCIO Cause of Injury Code_57.0',
 'WCIO Cause of Injury Code_58.0',
 'WCIO Cause of Injury Code_59.0',
 'WCIO Cause of Injury Code_6.0',
 'WCIO Cause of Injury Code_60.0',
 'WCIO Cause of Injury Code_61.0',
 'WCIO Cause of Injury Code_65.0',
 'WCIO Cause of Injury Code_66.0',
 'WCIO Cause of Injury Code_67.0',
 'WCIO Cause of Injury Code_68.0',
 'WCIO Cause of Injury Code_69.0',
 'WCIO Cause of Injury Code_7.0',
 'WCIO Cause of Injury Code_70.0',
 'WCIO Cause of Injury Code_74.0',
 'WCIO Cause of Injury Code_75.0',
 'WCIO Cause of Injury Code_76.0',
 'WCIO Cause of Injury Code_77.0',
 'WCIO Cause of Injury Code_78.0',
 'WCIO Cause of Injury Code_79.0',
 'WCIO Cause of Injury Code_8.0',
 'WCIO Cause of Injury Code_80.0',
 'WCIO Cause of Injury Code_81.0',
 'WCIO Cause of Injury Code_82.0',
 'WCIO Cause of Injury Code_83.0',
 'WCIO Cause of Injury Code_84.0',
 'WCIO Cause of Injury Code_85.0',
 'WCIO Cause of Injury Code_86.0',
 'WCIO Cause of Injury Code_87.0',
 'WCIO Cause of Injury Code_88.0',
 'WCIO Cause of Injury Code_89.0',
 'WCIO Cause of Injury Code_9.0',
 'WCIO Cause of Injury Code_90.0',
 'WCIO Cause of Injury Code_91.0',
 'WCIO Cause of Injury Code_93.0',
 'WCIO Cause of Injury Code_94.0',
 'WCIO Cause of Injury Code_95.0',
 'WCIO Cause of Injury Code_96.0',
 'WCIO Cause of Injury Code_97.0',
 'WCIO Cause of Injury Code_98.0',
 'WCIO Cause of Injury Code_99.0',
 'WCIO Cause of Injury Code_nan',
 'WCIO Nature of Injury Code_1.0',
 'WCIO Nature of Injury Code_10.0',
 'WCIO Nature of Injury Code_13.0',
 'WCIO Nature of Injury Code_16.0',
 'WCIO Nature of Injury Code_19.0',
 'WCIO Nature of Injury Code_2.0',
 'WCIO Nature of Injury Code_22.0',
 'WCIO Nature of Injury Code_25.0',
 'WCIO Nature of Injury Code_28.0',
 'WCIO Nature of Injury Code_3.0',
 'WCIO Nature of Injury Code_30.0',
 'WCIO Nature of Injury Code_31.0',
 'WCIO Nature of Injury Code_32.0',
 'WCIO Nature of Injury Code_34.0',
 'WCIO Nature of Injury Code_36.0',
 'WCIO Nature of Injury Code_37.0',
 'WCIO Nature of Injury Code_38.0',
 'WCIO Nature of Injury Code_4.0',
 'WCIO Nature of Injury Code_40.0',
 'WCIO Nature of Injury Code_41.0',
 'WCIO Nature of Injury Code_42.0',
 'WCIO Nature of Injury Code_43.0',
 'WCIO Nature of Injury Code_46.0',
 'WCIO Nature of Injury Code_47.0',
 'WCIO Nature of Injury Code_49.0',
 'WCIO Nature of Injury Code_52.0',
 'WCIO Nature of Injury Code_53.0',
 'WCIO Nature of Injury Code_54.0',
 'WCIO Nature of Injury Code_55.0',
 'WCIO Nature of Injury Code_58.0',
 'WCIO Nature of Injury Code_59.0',
 'WCIO Nature of Injury Code_60.0',
 'WCIO Nature of Injury Code_61.0',
 'WCIO Nature of Injury Code_62.0',
 'WCIO Nature of Injury Code_63.0',
 'WCIO Nature of Injury Code_64.0',
 'WCIO Nature of Injury Code_65.0',
 'WCIO Nature of Injury Code_66.0',
 'WCIO Nature of Injury Code_67.0',
 'WCIO Nature of Injury Code_68.0',
 'WCIO Nature of Injury Code_69.0',
 'WCIO Nature of Injury Code_7.0',
 'WCIO Nature of Injury Code_70.0',
 'WCIO Nature of Injury Code_71.0',
 'WCIO Nature of Injury Code_72.0',
 'WCIO Nature of Injury Code_73.0',
 'WCIO Nature of Injury Code_74.0',
 'WCIO Nature of Injury Code_75.0',
 'WCIO Nature of Injury Code_76.0',
 'WCIO Nature of Injury Code_77.0',
 'WCIO Nature of Injury Code_78.0',
 'WCIO Nature of Injury Code_79.0',
 'WCIO Nature of Injury Code_80.0',
 'WCIO Nature of Injury Code_83.0',
 'WCIO Nature of Injury Code_90.0',
 'WCIO Nature of Injury Code_91.0',
 'WCIO Nature of Injury Code_nan',
 'WCIO Part Of Body Code_-9.0',
 'WCIO Part Of Body Code_10.0',
 'WCIO Part Of Body Code_11.0',
 'WCIO Part Of Body Code_12.0',
 'WCIO Part Of Body Code_13.0',
 'WCIO Part Of Body Code_14.0',
 'WCIO Part Of Body Code_15.0',
 'WCIO Part Of Body Code_16.0',
 'WCIO Part Of Body Code_17.0',
 'WCIO Part Of Body Code_18.0',
 'WCIO Part Of Body Code_19.0',
 'WCIO Part Of Body Code_20.0',
 'WCIO Part Of Body Code_21.0',
 'WCIO Part Of Body Code_22.0',
 'WCIO Part Of Body Code_23.0',
 'WCIO Part Of Body Code_24.0',
 'WCIO Part Of Body Code_25.0',
 'WCIO Part Of Body Code_26.0',
 'WCIO Part Of Body Code_30.0',
 'WCIO Part Of Body Code_31.0',
 'WCIO Part Of Body Code_32.0',
 'WCIO Part Of Body Code_33.0',
 'WCIO Part Of Body Code_34.0',
 'WCIO Part Of Body Code_35.0',
 'WCIO Part Of Body Code_36.0',
 'WCIO Part Of Body Code_37.0',
 'WCIO Part Of Body Code_38.0',
 'WCIO Part Of Body Code_39.0',
 'WCIO Part Of Body Code_40.0',
 'WCIO Part Of Body Code_41.0',
 'WCIO Part Of Body Code_42.0',
 'WCIO Part Of Body Code_43.0',
 'WCIO Part Of Body Code_44.0',
 'WCIO Part Of Body Code_45.0',
 'WCIO Part Of Body Code_46.0',
 'WCIO Part Of Body Code_47.0',
 'WCIO Part Of Body Code_48.0',
 'WCIO Part Of Body Code_49.0',
 'WCIO Part Of Body Code_50.0',
 'WCIO Part Of Body Code_51.0',
 'WCIO Part Of Body Code_52.0',
 'WCIO Part Of Body Code_53.0',
 'WCIO Part Of Body Code_54.0',
 'WCIO Part Of Body Code_55.0',
 'WCIO Part Of Body Code_56.0',
 'WCIO Part Of Body Code_57.0',
 'WCIO Part Of Body Code_58.0',
 'WCIO Part Of Body Code_60.0',
 'WCIO Part Of Body Code_61.0',
 'WCIO Part Of Body Code_62.0',
 'WCIO Part Of Body Code_63.0',
 'WCIO Part Of Body Code_64.0',
 'WCIO Part Of Body Code_65.0',
 'WCIO Part Of Body Code_66.0',
 'WCIO Part Of Body Code_90.0',
 'WCIO Part Of Body Code_91.0',
 'WCIO Part Of Body Code_99.0',
 'WCIO Part Of Body Code_nan',
 'Has C-3 Date_0',
 'Has C-3 Date_1',
 'Has First Hearing Date_0',
 'Has First Hearing Date_1']


COUNTIES =[
    'ALBANY', 'ALLEGANY', 'BRONX', 'BROOME', 'CATTARAUGUS', 'CAYUGA', 'CHAUTAUQUA',
    'CHEMUNG', 'CHENANGO', 'CLINTON', 'COLUMBIA', 'CORTLAND', 'DELAWARE', 'DUTCHESS',
    'ERIE', 'ESSEX', 'FRANKLIN', 'FULTON', 'GENESEE', 'GREENE', 'HAMILTON', 'HERKIMER',
    'JEFFERSON', 'KINGS', 'LEWIS', 'LIVINGSTON', 'MADISON', 'MONROE', 'MONTGOMERY',
    'NASSAU', 'NEW YORK', 'NIAGARA', 'ONEIDA', 'ONONDAGA', 'ONTARIO', 'ORANGE',
    'ORLEANS', 'OSWEGO', 'OTSEGO', 'PUTNAM', 'QUEENS', 'RENSSELAER', 'RICHMOND',
    'ROCKLAND', 'SARATOGA', 'SCHENECTADY', 'SCHOHARIE', 'SCHUYLER', 'SENECA',
    'ST. LAWRENCE', 'STEUBEN', 'SUFFOLK', 'SULLIVAN', 'TIOGA', 'TOMPKINS', 'ULSTER',
    'UNKNOWN', 'WARREN', 'WASHINGTON', 'WAYNE', 'WESTCHESTER', 'WYOMING', 'YATES'
]

INDUSTRY_CODES = [
 'Industry Code_11.0',
 'Industry Code_21.0',
 'Industry Code_22.0',
 'Industry Code_23.0',
 'Industry Code_31.0',
 'Industry Code_32.0',
 'Industry Code_33.0',
 'Industry Code_42.0',
 'Industry Code_44.0',
 'Industry Code_45.0',
 'Industry Code_48.0',
 'Industry Code_49.0',
 'Industry Code_51.0',
 'Industry Code_52.0',
 'Industry Code_53.0',
 'Industry Code_54.0',
 'Industry Code_55.0',
 'Industry Code_56.0',
 'Industry Code_61.0',
 'Industry Code_62.0',
 'Industry Code_71.0',
 'Industry Code_72.0',
 'Industry Code_81.0',
 'Industry Code_92.0',
 'Industry Code_nan',
]

CAUSE_OF_INJURY_CODES = [
'WCIO Cause of Injury Code_1.0',
 'WCIO Cause of Injury Code_10.0',
 'WCIO Cause of Injury Code_11.0',
 'WCIO Cause of Injury Code_12.0',
 'WCIO Cause of Injury Code_13.0',
 'WCIO Cause of Injury Code_14.0',
 'WCIO Cause of Injury Code_15.0',
 'WCIO Cause of Injury Code_16.0',
 'WCIO Cause of Injury Code_17.0',
 'WCIO Cause of Injury Code_18.0',
 'WCIO Cause of Injury Code_19.0',
 'WCIO Cause of Injury Code_2.0',
 'WCIO Cause of Injury Code_20.0',
 'WCIO Cause of Injury Code_25.0',
 'WCIO Cause of Injury Code_26.0',
 'WCIO Cause of Injury Code_27.0',
 'WCIO Cause of Injury Code_28.0',
 'WCIO Cause of Injury Code_29.0',
 'WCIO Cause of Injury Code_3.0',
 'WCIO Cause of Injury Code_30.0',
 'WCIO Cause of Injury Code_31.0',
 'WCIO Cause of Injury Code_32.0',
 'WCIO Cause of Injury Code_33.0',
 'WCIO Cause of Injury Code_4.0',
 'WCIO Cause of Injury Code_40.0',
 'WCIO Cause of Injury Code_41.0',
 'WCIO Cause of Injury Code_45.0',
 'WCIO Cause of Injury Code_46.0',
 'WCIO Cause of Injury Code_47.0',
 'WCIO Cause of Injury Code_48.0',
 'WCIO Cause of Injury Code_5.0',
 'WCIO Cause of Injury Code_50.0',
 'WCIO Cause of Injury Code_52.0',
 'WCIO Cause of Injury Code_53.0',
 'WCIO Cause of Injury Code_54.0',
 'WCIO Cause of Injury Code_55.0',
 'WCIO Cause of Injury Code_56.0',
 'WCIO Cause of Injury Code_57.0',
 'WCIO Cause of Injury Code_58.0',
 'WCIO Cause of Injury Code_59.0',
 'WCIO Cause of Injury Code_6.0',
 'WCIO Cause of Injury Code_60.0',
 'WCIO Cause of Injury Code_61.0',
 'WCIO Cause of Injury Code_65.0',
 'WCIO Cause of Injury Code_66.0',
 'WCIO Cause of Injury Code_67.0',
 'WCIO Cause of Injury Code_68.0',
 'WCIO Cause of Injury Code_69.0',
 'WCIO Cause of Injury Code_7.0',
 'WCIO Cause of Injury Code_70.0',
 'WCIO Cause of Injury Code_74.0',
 'WCIO Cause of Injury Code_75.0',
 'WCIO Cause of Injury Code_76.0',
 'WCIO Cause of Injury Code_77.0',
 'WCIO Cause of Injury Code_78.0',
 'WCIO Cause of Injury Code_79.0',
 'WCIO Cause of Injury Code_8.0',
 'WCIO Cause of Injury Code_80.0',
 'WCIO Cause of Injury Code_81.0',
 'WCIO Cause of Injury Code_82.0',
 'WCIO Cause of Injury Code_83.0',
 'WCIO Cause of Injury Code_84.0',
 'WCIO Cause of Injury Code_85.0',
 'WCIO Cause of Injury Code_86.0',
 'WCIO Cause of Injury Code_87.0',
 'WCIO Cause of Injury Code_88.0',
 'WCIO Cause of Injury Code_89.0',
 'WCIO Cause of Injury Code_9.0',
 'WCIO Cause of Injury Code_90.0',
 'WCIO Cause of Injury Code_91.0',
 'WCIO Cause of Injury Code_93.0',
 'WCIO Cause of Injury Code_94.0',
 'WCIO Cause of Injury Code_95.0',
 'WCIO Cause of Injury Code_96.0',
 'WCIO Cause of Injury Code_97.0',
 'WCIO Cause of Injury Code_98.0',
 'WCIO Cause of Injury Code_99.0',
 'WCIO Cause of Injury Code_nan',
 ]

NATURE_OF_INJURY_CODES = [
'WCIO Nature of Injury Code_1.0',
 'WCIO Nature of Injury Code_10.0',
 'WCIO Nature of Injury Code_13.0',
 'WCIO Nature of Injury Code_16.0',
 'WCIO Nature of Injury Code_19.0',
 'WCIO Nature of Injury Code_2.0',
 'WCIO Nature of Injury Code_22.0',
 'WCIO Nature of Injury Code_25.0',
 'WCIO Nature of Injury Code_28.0',
 'WCIO Nature of Injury Code_3.0',
 'WCIO Nature of Injury Code_30.0',
 'WCIO Nature of Injury Code_31.0',
 'WCIO Nature of Injury Code_32.0',
 'WCIO Nature of Injury Code_34.0',
 'WCIO Nature of Injury Code_36.0',
 'WCIO Nature of Injury Code_37.0',
 'WCIO Nature of Injury Code_38.0',
 'WCIO Nature of Injury Code_4.0',
 'WCIO Nature of Injury Code_40.0',
 'WCIO Nature of Injury Code_41.0',
 'WCIO Nature of Injury Code_42.0',
 'WCIO Nature of Injury Code_43.0',
 'WCIO Nature of Injury Code_46.0',
 'WCIO Nature of Injury Code_47.0',
 'WCIO Nature of Injury Code_49.0',
 'WCIO Nature of Injury Code_52.0',
 'WCIO Nature of Injury Code_53.0',
 'WCIO Nature of Injury Code_54.0',
 'WCIO Nature of Injury Code_55.0',
 'WCIO Nature of Injury Code_58.0',
 'WCIO Nature of Injury Code_59.0',
 'WCIO Nature of Injury Code_60.0',
 'WCIO Nature of Injury Code_61.0',
 'WCIO Nature of Injury Code_62.0',
 'WCIO Nature of Injury Code_63.0',
 'WCIO Nature of Injury Code_64.0',
 'WCIO Nature of Injury Code_65.0',
 'WCIO Nature of Injury Code_66.0',
 'WCIO Nature of Injury Code_67.0',
 'WCIO Nature of Injury Code_68.0',
 'WCIO Nature of Injury Code_69.0',
 'WCIO Nature of Injury Code_7.0',
 'WCIO Nature of Injury Code_70.0',
 'WCIO Nature of Injury Code_71.0',
 'WCIO Nature of Injury Code_72.0',
 'WCIO Nature of Injury Code_73.0',
 'WCIO Nature of Injury Code_74.0',
 'WCIO Nature of Injury Code_75.0',
 'WCIO Nature of Injury Code_76.0',
 'WCIO Nature of Injury Code_77.0',
 'WCIO Nature of Injury Code_78.0',
 'WCIO Nature of Injury Code_79.0',
 'WCIO Nature of Injury Code_80.0',
 'WCIO Nature of Injury Code_83.0',
 'WCIO Nature of Injury Code_90.0',
 'WCIO Nature of Injury Code_91.0',
 'WCIO Nature of Injury Code_nan',
 ]

PART_OF_BODY_CODES = [
 'WCIO Part Of Body Code_-9.0',
 'WCIO Part Of Body Code_10.0',
 'WCIO Part Of Body Code_11.0',
 'WCIO Part Of Body Code_12.0',
 'WCIO Part Of Body Code_13.0',
 'WCIO Part Of Body Code_14.0',
 'WCIO Part Of Body Code_15.0',
 'WCIO Part Of Body Code_16.0',
 'WCIO Part Of Body Code_17.0',
 'WCIO Part Of Body Code_18.0',
 'WCIO Part Of Body Code_19.0',
 'WCIO Part Of Body Code_20.0',
 'WCIO Part Of Body Code_21.0',
 'WCIO Part Of Body Code_22.0',
 'WCIO Part Of Body Code_23.0',
 'WCIO Part Of Body Code_24.0',
 'WCIO Part Of Body Code_25.0',
 'WCIO Part Of Body Code_26.0',
 'WCIO Part Of Body Code_30.0',
 'WCIO Part Of Body Code_31.0',
 'WCIO Part Of Body Code_32.0',
 'WCIO Part Of Body Code_33.0',
 'WCIO Part Of Body Code_34.0',
 'WCIO Part Of Body Code_35.0',
 'WCIO Part Of Body Code_36.0',
 'WCIO Part Of Body Code_37.0',
 'WCIO Part Of Body Code_38.0',
 'WCIO Part Of Body Code_39.0',
 'WCIO Part Of Body Code_40.0',
 'WCIO Part Of Body Code_41.0',
 'WCIO Part Of Body Code_42.0',
 'WCIO Part Of Body Code_43.0',
 'WCIO Part Of Body Code_44.0',
 'WCIO Part Of Body Code_45.0',
 'WCIO Part Of Body Code_46.0',
 'WCIO Part Of Body Code_47.0',
 'WCIO Part Of Body Code_48.0',
 'WCIO Part Of Body Code_49.0',
 'WCIO Part Of Body Code_50.0',
 'WCIO Part Of Body Code_51.0',
 'WCIO Part Of Body Code_52.0',
 'WCIO Part Of Body Code_53.0',
 'WCIO Part Of Body Code_54.0',
 'WCIO Part Of Body Code_55.0',
 'WCIO Part Of Body Code_56.0',
 'WCIO Part Of Body Code_57.0',
 'WCIO Part Of Body Code_58.0',
 'WCIO Part Of Body Code_60.0',
 'WCIO Part Of Body Code_61.0',
 'WCIO Part Of Body Code_62.0',
 'WCIO Part Of Body Code_63.0',
 'WCIO Part Of Body Code_64.0',
 'WCIO Part Of Body Code_65.0',
 'WCIO Part Of Body Code_66.0',
 'WCIO Part Of Body Code_90.0',
 'WCIO Part Of Body Code_91.0',
 'WCIO Part Of Body Code_99.0',
 'WCIO Part Of Body Code_nan',
]

COUNTIES = [
'Carrier Type_UNKNOWN',
 'County of Injury_ALBANY',
 'County of Injury_ALLEGANY',
 'County of Injury_BRONX',
 'County of Injury_BROOME',
 'County of Injury_CATTARAUGUS',
 'County of Injury_CAYUGA',
 'County of Injury_CHAUTAUQUA',
 'County of Injury_CHEMUNG',
 'County of Injury_CHENANGO',
 'County of Injury_CLINTON',
 'County of Injury_COLUMBIA',
 'County of Injury_CORTLAND',
 'County of Injury_DELAWARE',
 'County of Injury_DUTCHESS',
 'County of Injury_ERIE',
 'County of Injury_ESSEX',
 'County of Injury_FRANKLIN',
 'County of Injury_FULTON',
 'County of Injury_GENESEE',
 'County of Injury_GREENE',
 'County of Injury_HAMILTON',
 'County of Injury_HERKIMER',
 'County of Injury_JEFFERSON',
 'County of Injury_KINGS',
 'County of Injury_LEWIS',
 'County of Injury_LIVINGSTON',
 'County of Injury_MADISON',
 'County of Injury_MONROE',
 'County of Injury_MONTGOMERY',
 'County of Injury_NASSAU',
 'County of Injury_NEW YORK',
 'County of Injury_NIAGARA',
 'County of Injury_ONEIDA',
 'County of Injury_ONONDAGA',
 'County of Injury_ONTARIO',
 'County of Injury_ORANGE',
 'County of Injury_ORLEANS',
 'County of Injury_OSWEGO',
 'County of Injury_OTSEGO',
 'County of Injury_PUTNAM',
 'County of Injury_QUEENS',
 'County of Injury_RENSSELAER',
 'County of Injury_RICHMOND',
 'County of Injury_ROCKLAND',
 'County of Injury_SARATOGA',
 'County of Injury_SCHENECTADY',
 'County of Injury_SCHOHARIE',
 'County of Injury_SCHUYLER',
 'County of Injury_SENECA',
 'County of Injury_ST. LAWRENCE',
 'County of Injury_STEUBEN',
 'County of Injury_SUFFOLK',
 'County of Injury_SULLIVAN',
 'County of Injury_TIOGA',
 'County of Injury_TOMPKINS',
 'County of Injury_ULSTER',
 'County of Injury_UNKNOWN',
 'County of Injury_WARREN',
 'County of Injury_WASHINGTON',
 'County of Injury_WAYNE',
 'County of Injury_WESTCHESTER',
 'County of Injury_WYOMING',
 'County of Injury_YATES',
]